### ISSUE TITLE
Autohotkey dependency downloaded wrong version

### ISSUE THREAD

**Issue by adripo** [HunterZ/choco#10]
The uninstaller script has autohotkey as dependency
https://github.com/HunterZ/choco/blob/master/msiafterburner/msiafterburner.nuspec#L19

The specified version is ignored and it automatically download latest (2.0.2)
The uninstall script is written for version 1 so it fails when uninstalling.

Can you upgrade the script for v2?

**Comment by HunterZ** [comment]
Closing - someone else has taken over maintenance of this package: https://github.com/mikeee/ChocoPackages/tree/master/automatic/msiafterburner
