### ISSUE TITLE
suggested fix for needing token

### ISSUE THREAD

**Issue by mabelrxu** [HunterZ/choco#2]
make $url line like this:
`$url = 'http://download.msi.com/uti_exe/vga/MSIAfterburnerSetup.zip?__token__=' + $(Invoke-RestMethod https://www.msi.com/api/v1/get_token)`

**Comment by mabelrxu** [comment]
also then hash will be like this:
c9c487321c44982a54e9a7f016b4d3e91394c23f424976f9dfa40c99e5f9fb95

**Comment by HunterZ** [comment]
Closing this, as I fixed it a while ago. Turns out you also need to pass a timestamp to the token request endpoint, or else you might get the wrong token back, resulting in a failed download.
