### ISSUE TITLE
msiafterburner: create desktop shortcut for RTSS

### ISSUE THREAD

**Issue by soredake** [HunterZ/choco#6]
MSI Afterburner installer additionally installs RTSS at `C:\Program Files (x86)\RivaTuner Statistics Server\RTSS.exe` but it does not create a shortcut on desktop, maybe msiafterpackage can create this shortcut by default?

**Comment by HunterZ** [comment]
Unfortunately I don't think there's anything I can do here. I'm pretty sure any desktop shortcuts are created by the underlying installer from MSI and not by Chocolatey tooling.

The fact that MSIAfterburner installs RTSS under the hood is extremely awkward in general, and not well supported by Chocolatey.

**Comment by soredake** [comment]
Shortcut can be added with choco function https://github.com/AdmiringWorm/chocolatey-packages/blob/master/automatic/origin/tools/helpers.ps1#L92

**Comment by soredake** [comment]
https://github.com/ark0f/choco-ryujinx/commit/dd136a524af245a0a36cbe1bc7ffddc4f294a57e another example

**Comment by soredake** [comment]
@HunterZ hello, i've created pr to fix this issue https://github.com/HunterZ/choco/pull/7

**Comment by HunterZ** [comment]
FYI, someone else has taken over maintenance of this chocolatey package. You might try contacting them: https://github.com/mikeee/ChocoPackages/tree/master/automatic/msiafterburner
